name: Scopes
version: "1.0"

# ghc-options: -Wall

dependencies:
  - base > 4.14 # > 4.4 && < 4.14
  - syz
  - syb
  - ZipperAG
#  - Strafunski-StrategyLib
  - haskell-src
#  - mtl
  - transformers
#  - random
#  - QuickCheck
  - template-haskell
#  - HaLeX
#  - criterion
#  - uulib
#   - bytestring


library:
  source-dirs: .